FORMAT: 1A
HOST: http://app.apiary.io/mydiary21/

# My Diary App

My diary app is an online journal where users can save their thoughts and feelings.

## User [/auth/signup]

### Create User [POST]

+ Request (application/json)

            {
                "name" : "Test_User",
                "email" : "testemail2@yahoo.com",
                "password" : "test"
            }
+ Response 201 (application/json)


    + Body

            {
                "token": "valid token"
            }
            
+ Response 400 (application/json)

    + Body
    
            {
                "message": "missing field"
            }
            
            
      
## User [/auth/signin]

### Login User [POST]

+ Request (application/json)

            {
                "email" : "testemail2@yahoo.com",
                "password" : "test"
            }
+ Response 200 (application/json)


    + Body

            {
                "token": "valid token"
            }
+ Response 400 (application/json)

    + Body
    
            {
                "message": "missing field"
            }
            
          


## Entry [/entries]

### List All Entries [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user_id": 1,
                "title": "test title",
                "content": "test content",
                "date_created": "2018-10-14T23:00:00.000Z"
            }
        ]

### Create Entry [POST]


+ Request (application/json)

        {
            "title": "test title 1",
            "content": "test content"
        }

+ Response 201 (application/json)


    + Body

            {
                "id": 2,
                "user_id": 1,
                "title": "test title 1",
                "content": "test content",
                "date_created": "2018-10-14T23:00:00.000Z"
            }
            
+ Response 400 (application/json)

    + Body
    
            {
                "message": "missing field"
            }
            
            
+ Response 401 (application/json)  

    + Body
    
            {
                "message": "unauthorized"
            }
                         
            
            
## Entry [/entries/{id}]

    + Parameter
        
        + id: 1 (number) - An unique identifier of an entry.
            
            
### Get One Entry [GET]
+ Response 200 (application/json)

        [
            {
                "id": 1,
                "user_id": 1,
                "title": "test title",
                "content": "test content",
                "date_created": "2018-10-14T23:00:00.000Z"
            }
        ]
        
+ Response 401 (application/json)  

    + Body
    
            {
                "message": "unauthorized"
            }
             

### Modify Entry [PUT]

+ Request (application/json)

        {
            "title": "modify test title 1",
            "content": "modify test content"
        }

+ Response 200 (application/json)


    + Body

            {
                "id": 2,
                "user_id": 1,
                "title": "modify test title 1",
                "content": "modify test content",
                "date_created": "2018-10-14T23:00:00.000Z"
            }
            
+ Response 401 (application/json)  

    + Body
    
            {
                "message": "unauthorized"
            }
             
            
            
### Delete Entry [DELETE]
+ Response 200 (application/json)


    + Body

            {
                "message" : "entry deleted"
            }
            
+ Response 401 (application/json)  

    + Body
    
            {
                "message": "unauthorized"
            }